### ISSUE TITLE
Missing .md extension on Using Git file

### ISSUE THREAD

**Issue by sinksc** [FRCTeam3206/Team3206Onboarding#1]
Missing `.md` extension on this file:
https://github.com/FRCTeam3206/Team3206Onboarding/blob/cee241835795f77139c0e3191c16e45cf46f7dc5/Using_git_and_GitHub

**Comment by crschardt** [comment]
That was silly of me. Main isn't protected yet, so feel free to merge directly.

**Comment by sinksc** [comment]
I think I need to be added as a collaborator first. I don't see an option to merge my PR
